project_id = "oxxioffwasbwbsinbowi"

[functions.outlook-callback]
verify_jwt = false

[functions.gmail-callback]
verify_jwt = false

[functions.extract-receipt]
verify_jwt = false

[functions.auto-match]
verify_jwt = false
