project_id = "cevmfwrcpwnyijqabspx"

[functions.outlook-callback]
verify_jwt = false

[functions.gmail-callback]
verify_jwt = false

[functions.extract-receipt]
verify_jwt = false

[functions.auto-match]
verify_jwt = false

[functions.bank-callback]
verify_jwt = false

[functions.bank-sync]
verify_jwt = false